version: '2'
volumes:
    sense-data:
    dashboard-data:
    resin-data:
services:

  influxdb:
    restart: always
    image: arm32v7/influxdb@sha256:2fed9b09a672cab330ac3ea1f03616e6821f2235bda64d549f605ef0d7081911
    volumes:
      - 'sense-data:/var/lib/influxdb'
  node-red:
    build: ./node-red
    volumes:
      - 'resin-data:/data'
    restart: always
    privileged: true
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
    environment:
      - "USERNAME=balena"
      - "PASSWORD=balena"
      - "ENCRIPTION_KEY=balena"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      - 80:80
  dashboard:
    image: bh.cr/balenalabs/dashboard
    restart: always
    volumes:
        - 'dashboard-data:/data'
    ports:
        - '100'
  sensor:
    build: .
    privileged: true
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.supervisor-api: '1'
    expose:
      - '7575'
    environment:
      RAW_VALUES: '0'
      COLLAPSE_FIELDS: '1'
  connector:
    image: bh.cr/balenalabs/connector-armv7hf
    restart: always
    labels:
      io.balena.features.balena-api: '1'
    privileged: true
    ports:
      - "8080"
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always  

